POST http://localhost:8080/v1/phone
Content-Type: application/json

{   
    "phone": "010-1233-1233",
    "name": "허동욱"
}

###

POST http://localhost:8080/v1/phone/veri
Content-Type: application/json

{
    "phone": "010-1233-1233",
    "name": "허동욱",
    "code": "123456789"
}

###
